### ISSUE TITLE
Viewing Module List Error

### ISSUE THREAD

**Issue by Felli** [petersmithca/humhub-adsense#1]
So out of the sake of testing, after enabling the module this worked out fine, but when trying to enter the module list to disable I got an internal server error.
### Example

Entering http://yourdomain.com/admin/module/list throws off an internal server error, which I have no idea how if it follows the same logic as the Basic Chat module, will be doing some messing around while I'm at it to see if I can fix this.

**Comment by Felli** [comment]
The issue would be that of the Birthday module not playing well with the Adsense module for some reason.

**Comment by Felli** [comment]
Quick fix: Remove Birthday & AdSense module then delete their entries in the table `module_enabled` of your database after this you should be able to enable both modules again.

**Comment by petersmithca** [comment]
I'll see if I can duplicate at some point, very odd
